version: "3"
services:
  strapi:
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"