#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function walk(dir) {
  const files = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const res = path.resolve(dir, e.name);
    if (e.isDirectory()) files.push(...walk(res));
    else files.push(res);
  }
  return files;
}

function pluralize(name) {
  if (name.endsWith('y')) return name.slice(0, -1) + 'ies';
  return name + 's';
}

function scanApis(apiRoot) {
  if (!fs.existsSync(apiRoot)) return [];
  const apis = fs.readdirSync(apiRoot, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
  return apis;
}

function buildOpenApi(apis) {
  const lines = [];
  lines.push('openapi: 3.0.3');
  lines.push('info:');
  lines.push('  title: cc_blog API');
  lines.push('  version: "1.0.0"');
  lines.push('  description: "Auto-generated OpenAPI spec for this repository\'s Strapi content-type APIs."');
  lines.push('servers:');
  lines.push('  - url: http://localhost:1337');
  lines.push('    description: Local development server');
  lines.push('paths:');

  for (const api of apis) {
    const plural = pluralize(api);
    const base = `/api/${plural}`;
    lines.push(`  ${base}:`);
    lines.push('    get:');
    lines.push(`      summary: List ${plural}`);
    lines.push('      responses:');
    lines.push("        '200':");
    lines.push('          description: OK');
    lines.push('    post:');
    lines.push(`      summary: Create ${api}`);
    lines.push('      requestBody:');
    lines.push('        required: true');
    lines.push('        content:');
    lines.push('          application/json:');
    lines.push('            schema:');
    lines.push(`              $ref: '#/components/schemas/${capitalize(api)}'`);
    lines.push("      responses:");
    lines.push("        '201':");
    lines.push('          description: Created');
    lines.push('  ' + base + '/{id}:');
    lines.push('    parameters:');
    lines.push('      - in: path');
    lines.push('        name: id');
    lines.push('        required: true');
    lines.push('        schema:');
    lines.push('          type: string');
    lines.push('    get:');
    lines.push('      summary: Get by ID');
    lines.push("      responses:");
    lines.push("        '200':");
    lines.push('          description: OK');
    lines.push('    put:');
    lines.push('      summary: Update (replace)');
    lines.push('      requestBody:');
    lines.push('        required: true');
    lines.push('        content:');
    lines.push('          application/json:');
    lines.push('            schema:');
    lines.push(`              $ref: '#/components/schemas/${capitalize(api)}'`);
    lines.push("      responses:");
    lines.push("        '200':");
    lines.push('          description: Updated');
    lines.push('    patch:');
    lines.push('      summary: Update (partial)');
    lines.push('      requestBody:');
    lines.push('        required: true');
    lines.push('        content:');
    lines.push('          application/json:');
    lines.push('            schema:');
    lines.push(`              $ref: '#/components/schemas/${capitalize(api)}'`);
    lines.push("      responses:");
    lines.push("        '200':");
    lines.push('          description: Updated');
    lines.push('    delete:');
    lines.push('      summary: Delete');
    lines.push("      responses:");
    lines.push("        '204':");
    lines.push('          description: No Content');
    lines.push('');
  }

  lines.push('components:');
  lines.push('  schemas:');
  for (const api of apis) {
    lines.push(`    ${capitalize(api)}:`);
    lines.push('      type: object');
    lines.push('      properties:');
    lines.push('        id:');
    lines.push('          type: integer');
    lines.push('        name:');
    lines.push('          type: string');
    lines.push('');
  }

  return lines.join('\n');
}

function capitalize(s) {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/-([a-z])/g, (m, p1) => p1.toUpperCase());
}

function buildMd(apis) {
  const lines = [];
  lines.push('# cc_blog API Documentation');
  lines.push('');
  lines.push('This file was auto-generated by `scripts/generate_api_docs.js`.');
  lines.push('');
  lines.push('Base URL');
  lines.push(' - Local: `http://localhost:1337`');
  lines.push('');
  lines.push('Endpoints');
  for (const api of apis) {
    const plural = pluralize(api);
    lines.push(`- ${capitalize(api)}: \`GET /api/${plural}\`, \`GET /api/${plural}/{id}\`, \`POST /api/${plural}\`, \`PUT/PATCH /api/${plural}/{id}\`, \`DELETE /api/${plural}/{id}\``);
  }
  lines.push('');
  lines.push('Example: List resources');
  lines.push('```');
  lines.push('curl -X GET "http://localhost:1337/api/your-resource"');
  lines.push('```');
  return lines.join('\n');
}

function writeFiles(openapi, md) {
  fs.writeFileSync(path.resolve(process.cwd(), 'openapi.yaml'), openapi, 'utf8');
  fs.writeFileSync(path.resolve(process.cwd(), 'API_DOCUMENTATION.md'), md, 'utf8');
  console.log('Wrote openapi.yaml and API_DOCUMENTATION.md');
}

function main() {
  const apiRoot = path.resolve(process.cwd(), 'src', 'api');
  const apis = scanApis(apiRoot);
  if (apis.length === 0) {
    console.warn('No APIs found under src/api');
  }
  const openapi = buildOpenApi(apis);
  const md = buildMd(apis);
  writeFiles(openapi, md);

  const argv = process.argv.slice(2);
  if (argv.includes('--watch')) {
    // lazy load chokidar
    let chokidar;
    try {
      chokidar = require('chokidar');
    } catch (e) {
      console.error('To use --watch please install chokidar: npm install --save-dev chokidar');
      process.exit(1);
    }

    const watcher = chokidar.watch(path.join(apiRoot, '**/*'), { ignoreInitial: true });
    console.log('Watching for changes under src/api ...');
    watcher.on('all', (event, pathChanged) => {
      console.log('Change detected:', event, pathChanged);
      try {
        const apis2 = scanApis(apiRoot);
        const openapi2 = buildOpenApi(apis2);
        const md2 = buildMd(apis2);
        writeFiles(openapi2, md2);
      } catch (err) {
        console.error('Error regenerating docs', err);
      }
    });
  }
}

main();
